name: Deploy to Azure Function App (func-workshop-sarray)

on:
  push:
    branches:
      - capstone

env:
  AZURE_FUNCTIONAPP_NAME: 'func-workshop-sarray' 
  NODE_VERSION: '22.x'                           
  PACKAGE_PATH: '.'                              

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout Repository Code'
        uses: actions/checkout@v4

      - name: 'Setup Node.js Environment'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
